spring.application.name=pro-ready-features

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show.sql=true
spring.jpa.properties.hibernate.format_sql=true
server.port=8087

spring.datasource.url=jdbc:mysql://localhost:3306/test?useSSL=false
spring.datasource.username=root
spring.datasource.password=istiak

spring.jap.defer-datasource-initilizer=true
spring.sql.init.node=always
spring.sql.init.data-locations=classpath:data.sql

employeeService.base.url=http://localhost/8087

#logging configuration
logging.level.com.example.pro_ready_features.dto.EmployeeDTO=DEBUG
logging.level.com.example.pro_ready_features.dto.config=INFO
logging.level.root=debug

logging.pattern.console=%d [%c] --- %m%n
logging.file.name=application.log

#Actuatuors
management.endpoints.web.exposure.include=*
management.info.env.enabled=true
info.app.author=
